services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: khalta
      POSTGRES_PASSWORD: khalta
      POSTGRES_DB: khalta
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
