import { readFileSync, readdirSync, statSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import type { CandidateRecord } from '@khalta/engine';
import { validateCandidate } from '../src';

// The records are SYNTHETIC optimizer output (regenerated by the engine's optimizer tests with
// UPDATE_FIXTURES=1; the validator may not import the optimizer, so it only ever sees plain data).
const dir = join(dirname(fileURLToPath(import.meta.url)), 'fixtures');
const load = (name: string) =>
  JSON.parse(readFileSync(join(dir, `${name}.json`), 'utf8')) as CandidateRecord;
const NAMES = ['candidate-cheapest', 'candidate-characteristics', 'candidate-shortfall'];
const clone = <T>(x: T): T => JSON.parse(JSON.stringify(x)) as T;
const fails = (rec: CandidateRecord) =>
  validateCandidate(rec).mismatches.map((m) => `${m.kind}:${m.key}`);
const has = (rec: CandidateRecord, prefix: string) => fails(rec).some((m) => m.startsWith(prefix));
const rule = (rec: CandidateRecord, key: string, ruleset = 'ENGINEERING') =>
  rec.snapshot.rules.find((r) => r.key === key && r.ruleset === ruleset)!;

describe('a genuine candidate passes the independent validator', () => {
  for (const n of NAMES)
    it(n, () => {
      const rec = load(n);
      const v = validateCandidate(rec);
      expect(v.mismatches).toEqual([]);
      expect(v.status).toBe('pass');
      expect(v.evaluation.status).toBe('pass');
    });

  it('the fixtures cover a plain, a characteristic-heavy and a shortfall candidate', () => {
    expect(load('candidate-shortfall').requiresAuthorization).toBe(true);
    expect(load('candidate-characteristics').characteristics.length).toBeGreaterThan(2);
    expect(load('candidate-cheapest').requiresAuthorization).toBe(false);
  });
});

describe('corruption: every promise the optimizer makes is re-derived and refused when false', () => {
  const base = () => clone(load('candidate-cheapest'));

  it('proportions that no longer match the report (the evaluation check disagrees)', () => {
    const r = base();
    r.snapshot.lines[0]!.kgPerM3 = '301.000';
    expect(has(r, 'evaluation:')).toBe(true);
    expect(has(r, 'rounding:')).toBe(true);
  });

  it('quantities off the practical grid', () => {
    const r = base();
    const cem = r.snapshot.lines.find((l) => l.materialId === 'cem-i')!;
    cem.kgPerM3 = (Number(cem.kgPerM3) + 1).toFixed(3);
    expect(has(r, 'rounding:rounding.cem-i')).toBe(true);
    const w = base();
    w.snapshot.lines.find((l) => l.materialId === 'water')!.kgPerM3 = '200.500';
    expect(has(w, 'rounding:rounding.water')).toBe(true);
    const a = base();
    for (const l of a.snapshot.lines.filter((x) => ['crusher', 'c20'].includes(x.materialId)))
      l.kgPerM3 = (Number(l.kgPerM3) + 2).toFixed(3);
    expect(has(a, 'rounding:rounding.aggregates')).toBe(true);
  });

  it('a material that is not usable: untested, expired, unpriced, excluded or not included', () => {
    const noTest = base();
    noTest.snapshot.materials.find((m) => m.id === 'c20')!.test = null;
    expect(has(noTest, 'availability:availability.c20')).toBe(true);
    const expired = base();
    expired.snapshot.materials.find((m) => m.id === 'c20')!.test!.freshness = 'expired';
    expect(has(expired, 'availability:availability.c20')).toBe(true);
    const unpriced = base();
    unpriced.snapshot.materials.find((m) => m.id === 'c20')!.price = { status: 'unavailable' };
    expect(has(unpriced, 'availability:availability.c20')).toBe(true);
    const excl = base();
    excl.materials = { exclude: ['c20'] };
    expect(has(excl, 'availability:availability.c20')).toBe(true);
    const incl = base();
    incl.materials = { include: ['cem-i'] };
    expect(has(incl, 'availability:availability.c20')).toBe(true);
    const fiber = base();
    fiber.snapshot.materials.find((m) => m.id === 'sp')!.category = 'fiber';
    expect(has(fiber, 'availability:availability.sp')).toBe(true);
    const gone = base();
    gone.snapshot.materials = gone.snapshot.materials.filter((m) => m.id !== 'c20');
    expect(has(gone, 'availability:availability.c20')).toBe(true);
  });

  it('a mix without water, cement or aggregate', () => {
    const r = base();
    r.snapshot.lines = r.snapshot.lines.filter((l) => l.materialId !== 'water');
    expect(has(r, 'configuration:composition.water')).toBe(true);
  });

  it('guardrail figures that are not what the sieve data give', () => {
    const cf = base();
    cf.guardrails.coarsenessFactor += 1;
    expect(has(cf, 'guardrail:guardrails.cf')).toBe(true);
    const wf = base();
    wf.guardrails.workabilityFactorAdjusted += 1;
    expect(has(wf, 'guardrail:guardrails.wf_adjusted')).toBe(true);
    const fines = base();
    fines.guardrails.finesPct += 1;
    expect(has(fines, 'guardrail:guardrails.fines')).toBe(true);
    const g = base();
    g.guardrails.gradingSieves[0]!.passing_pct += 3;
    expect(has(g, 'guardrail:grading@')).toBe(true);
    const t = base();
    t.guardrails.gradingSieves[0]!.target_pct += 3;
    expect(has(t, 'guardrail:grading.target@')).toBe(true);
    const missing = base();
    missing.guardrails.gradingSieves = missing.guardrails.gradingSieves.slice(1);
    expect(has(missing, 'guardrail:grading@')).toBe(true);
    const d = base();
    d.guardrails.dmaxMm = 19;
    expect(has(d, 'guardrail:guardrails.dmax')).toBe(true);
  });

  it('limits that the proportions really break', () => {
    const band = base();
    rule(band, 'eng.grading.target.band_pct').value = 1;
    expect(has(band, 'guardrail:grading@')).toBe(true);
    const cf = base();
    rule(cf, 'eng.shilstone.cf.min').value = 70;
    expect(has(cf, 'guardrail:cf')).toBe(true);
    const wf = base();
    rule(wf, 'eng.shilstone.wf.min').value = 40;
    expect(has(wf, 'guardrail:wf')).toBe(true);
    const fines = base();
    rule(fines, 'eng.fines.max_pct_75um').value = 0.1;
    expect(has(fines, 'guardrail:fines')).toBe(true);
    const pump = base();
    pump.snapshot.request.pumpable = true;
    rule(pump, 'eng.pumpable.min_passing_0_3mm_pct').value = 60;
    expect(has(pump, 'guardrail:pumpable')).toBe(true);
    const ind = base();
    rule(ind, 'grading.coarse.limits', 'ACI').value = [
      { sieve_mm: 9.5, min_pct: 90, max_pct: 100 },
    ];
    expect(has(ind, 'guardrail:grading.individual.')).toBe(true);
  });

  it('parameters that are not on file are named, never assumed', () => {
    const r = base();
    rule(r, 'eng.grading.target.band_pct').value = null;
    expect(has(r, 'parameter_missing:eng.grading.target.band_pct')).toBe(true);
    const wf = base();
    rule(wf, 'eng.shilstone.wf.max').value = null;
    expect(has(wf, 'parameter_missing:eng.shilstone.wf')).toBe(true);
    const lim = base();
    rule(lim, 'grading.fine.limits', 'ACI').value = null;
    expect(has(lim, 'parameter_missing:ACI:grading.fine.limits')).toBe(true);
    const both = base();
    both.snapshot.mode = 'BOTH';
    expect(has(both, 'parameter_missing:JS:grading.fine.limits')).toBe(true);
    const pump = base();
    pump.snapshot.request.pumpable = true;
    rule(pump, 'eng.pumpable.min_passing_0_3mm_pct').value = null;
    expect(has(pump, 'parameter_missing:eng.pumpable.min_passing_0_3mm_pct')).toBe(true);
    const nmas = base();
    nmas.snapshot.request.nmasMm = null;
    expect(validateCandidate(nmas).status).toBe('fail');
  });

  it('Shilstone WF bounds given per NMAS are read for this NMAS', () => {
    const r = base();
    rule(r, 'eng.shilstone.wf.min').value = { '19': 28 };
    rule(r, 'eng.shilstone.wf.max').value = { '19': 45 };
    expect(validateCandidate(r).mismatches).toEqual([]);
    rule(r, 'eng.shilstone.wf.max').value = { '25': 45 };
    expect(has(r, 'parameter_missing:eng.shilstone.wf')).toBe(true);
  });

  it('cost, evidence and configuration claims', () => {
    const cost = base();
    cost.costJodPerM3 = '1.000';
    expect(has(cost, 'cost:cost')).toBe(true);
    const ev = base();
    ev.evidence = ev.evidence.filter((e) => e !== 'TRIAL_REQUIRED');
    expect(has(ev, 'evidence:evidence.TRIAL_REQUIRED')).toBe(true);
    const base2 = base();
    base2.evidence = base2.evidence.filter((e) => e !== 'MODEL_BASELINE');
    expect(has(base2, 'evidence:evidence.MODEL_BASELINE')).toBe(true);
    const hide = clone(load('candidate-shortfall'));
    hide.evidence = hide.evidence.filter((e) => e !== 'MODEL_PREDICTS_SHORTFALL');
    expect(has(hide, 'evidence:evidence.shortfall')).toBe(true);
    const auth = clone(load('candidate-shortfall'));
    auth.requiresAuthorization = false;
    expect(has(auth, 'evidence:authorization')).toBe(true);
    const cem = base();
    cem.configuration.cementId = 'nope';
    expect(has(cem, 'configuration:configuration.cement')).toBe(true);
    const scm = base();
    scm.configuration.scmPct = 3;
    expect(has(scm, 'configuration:configuration.scm')).toBe(true);
    const none = base();
    none.configuration.scmId = null;
    expect(has(none, 'configuration:configuration.scm')).toBe(true);
  });

  it('a verdict that is not pass', () => {
    const r = base();
    r.report.verdict = 'incomplete';
    expect(has(r, 'evaluation:verdict')).toBe(true);
    const cost = base();
    cost.report.cost.state = 'incomplete';
    expect(has(cost, 'cost:cost')).toBe(true);
  });

  it('a w/cm above the engineering ceiling that no user value pins there', () => {
    const r = clone(load('candidate-shortfall'));
    expect(validateCandidate(r).mismatches).toEqual([]);
    r.snapshot.characteristics = [];
    expect(has(r, 'guardrail:wcm.ceiling')).toBe(true);
    const range = clone(load('candidate-shortfall'));
    range.snapshot.characteristics = [
      { key: 'wcm', sub: null, spec: { mode: 'range', min: 0.5 }, origin: 'request' },
    ];
    expect(has(range, 'guardrail:wcm.ceiling')).toBe(false);
    const pair = clone(load('candidate-shortfall'));
    pair.snapshot.characteristics = [
      { key: 'binder_kg', sub: null, spec: { mode: 'fixed', value: 380 }, origin: 'request' },
      { key: 'water_kg', sub: null, spec: { mode: 'fixed', value: 190 }, origin: 'request' },
    ];
    expect(has(pair, 'guardrail:wcm.ceiling')).toBe(false);
  });

  it('characteristic rows that disagree with the proportions', () => {
    const r = clone(load('candidate-characteristics'));
    const cf = r.characteristics.find((c) => c.key === 'shilstone.cf')!;
    cf.achieved = 1;
    expect(has(r, 'characteristic:shilstone.cf')).toBe(true);
    const status = clone(load('candidate-characteristics'));
    status.characteristics.find((c) => c.key === 'shilstone.cf')!.status = 'deviated';
    expect(has(status, 'characteristic:shilstone.cf')).toBe(true);
    const stranger = clone(load('candidate-characteristics'));
    stranger.characteristics.push({ ...cf, key: 'wcm' });
    expect(has(stranger, 'characteristic:wcm')).toBe(true);
    const out = clone(load('candidate-characteristics'));
    out.snapshot.characteristics.find((c) => c.key === 'shilstone.cf')!.spec = {
      mode: 'range',
      min: 80,
      max: 90,
    };
    expect(has(out, 'characteristic:shilstone.cf')).toBe(true);
    const adm = clone(load('candidate-characteristics'));
    adm.characteristics.find((c) => c.key === 'admixture')!.achieved = 9;
    expect(has(adm, 'characteristic:admixture')).toBe(true);
    const evalRow = clone(load('candidate-characteristics'));
    const sand = evalRow.characteristics.find((c) => c.key === 'sand_ratio_pct')!;
    expect(sand).toBeDefined();
  });

  it('a record that is not even a snapshot is refused rather than trusted', () => {
    const r = base();
    (r.snapshot as { schema: number }).schema = 9;
    expect(validateCandidate(r).status).toBe('fail');
  });
});

describe('the validator stays independent of the optimizer', () => {
  it('candidate.ts imports no optimizer or evaluator calculation code', () => {
    const src = readFileSync(
      join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'candidate.ts'),
      'utf8',
    );
    const imports = src.split('\n').filter((l) => /^\s*(import|export)\b.*\bfrom\b/.test(l));
    for (const l of imports) {
      expect(l).not.toMatch(/optimizer/);
      expect(l).not.toMatch(/evaluate\/(?!types)/);
    }
    expect(statSync(dir).isDirectory()).toBe(true);
    expect(readdirSync(dir).length).toBeGreaterThanOrEqual(3);
  });
});
