// Labels for the PDF submittal, Arabic and English. Arabic wording is a draft for review (docs/i18n-review.md).
export type Lang = 'en' | 'ar' | 'both';
export const S = {
  title: ['Mix design submittal', 'مستند اعتماد الخلطة'],
  code: ['Design code', 'رمز التصميم'],
  version: ['Version', 'الإصدار'],
  state: ['Lifecycle state', 'حالة التصميم'],
  plant: ['Plant', 'المحطة'],
  printed: ['Printed', 'تاريخ الطباعة'],
  qr: ['Scan for the live version', 'امسح للوصول إلى الإصدار الحالي'],
  req: ['Requirements', 'المتطلبات'],
  strength: ['Specified strength', 'المقاومة المحددة'],
  basis: ['Basis', 'الأساس'],
  age: ['Test age (days)', 'عمر الفحص (يوم)'],
  exposure: ['Exposure classes', 'فئات التعرّض'],
  slump: ['Slump (mm)', 'الهبوط (ملم)'],
  nmas: ['Nominal max aggregate size (mm)', 'المقاس الاسمي الأقصى للركام (ملم)'],
  pumpable: ['Pumpable', 'قابل للضخ'],
  yes: ['Yes', 'نعم'],
  no: ['No', 'لا'],
  materials: ['Materials and sources', 'المواد ومصادرها'],
  material: ['Material', 'المادة'],
  category: ['Category', 'الفئة'],
  source: ['Test source', 'مصدر الفحص'],
  tested: ['Test date', 'تاريخ الفحص'],
  proportions: ['Proportions (kg/m³)', 'النسب (كغم/م³)'],
  ssd: ['SSD design', 'التصميم (SSD)'],
  batch: ['Batch weights', 'أوزان الخلطة'],
  batchNote: ['Latest batch instance', 'آخر خلطة تشغيلية'],
  compliance: ['Compliance checks', 'فحوص المطابقة'],
  check: ['Check', 'الفحص'],
  value: ['Value', 'القيمة'],
  limit: ['Limit', 'الحد'],
  status: ['Result', 'النتيجة'],
  governing: ['Governing clause', 'البند الحاكم'],
  evidence: ['Evidence', 'الدليل'],
  pass: ['Pass', 'مطابق'],
  fail: ['Fail', 'غير مطابق'],
  not_evaluated: ['Not evaluated', 'لم يُقيَّم'],
  strengthEv: ['Strength evidence', 'أدلة المقاومة'],
  fcr: ['Required average strength f′cr (MPa)', 'متوسط المقاومة المطلوب f′cr (ميغاباسكال)'],
  branch: ['Derivation by ruleset', 'الاشتقاق حسب مجموعة القواعد'],
  trial: ['Trial batches', 'الخلطات التجريبية'],
  noTrial: ['No trial batch is recorded.', 'لا توجد خلطة تجريبية مسجلة.'],
  specimens: ['Specimens at test age (MPa)', 'العينات عند عمر الفحص (ميغاباسكال)'],
  gradation: ['Combined grading', 'التدرج المركّب'],
  gradationNote: [
    'Percent passing against sieve size (mm), from the stored aggregate sieve analyses and the proportions above.',
    'نسبة المار مقابل مقاس المنخل (ملم)، من تحاليل المناخل المخزنة والنسب أعلاه.',
  ],
  chars: ['Specified characteristics', 'الخصائص المحددة'],
  requested: ['Requested', 'المطلوب'],
  achieved: ['Achieved', 'المتحقق'],
  origin: ['Origin', 'المصدر'],
  declared: ['User-declared material values', 'قيم مواد مصرّح بها من المستخدم'],
  approval: ['Approval', 'الاعتماد'],
  by: ['By', 'بواسطة'],
  on: ['Date', 'التاريخ'],
  meaning: ['Meaning', 'المعنى'],
  reason: ['Reason', 'السبب'],
  legacy: ['Approved outside Khalta; reference', 'معتمد خارج خلطة؛ المرجع'],
  notApprovedYet: ['No approval is recorded.', 'لا يوجد اعتماد مسجل.'],
  disclaimer: [
    'This document describes a mix design proposal. A design is approved for production only when its state above says so; trial batching and QC approval are required, and results depend on the materials actually used.',
    'يصف هذا المستند اقتراح تصميم خلطة. لا يكون التصميم معتمداً للإنتاج إلا إذا نصّت حالته أعلاه على ذلك؛ والخلطات التجريبية واعتماد ضبط الجودة مطلوبان، وتعتمد النتائج على المواد المستخدمة فعلاً.',
  ],
  watermarkTrial: ['NOT APPROVED — TRIAL ONLY', 'غير معتمد — للتجربة فقط'],
  watermarkSuperseded: ['SUPERSEDED', 'مُستبدَل'],
  watermarkRetired: ['RETIRED', 'متوقف نهائياً'],
  letterheadMissing: ['Company letterhead is not configured', 'ترويسة الشركة غير مُعدّة'],
} as const satisfies Record<string, readonly [string, string]>;
export type Key = keyof typeof S;

export const STATE: Record<string, [string, string]> = {
  draft: ['Draft', 'مسودة'],
  evaluated: ['Evaluated', 'مُقيَّم'],
  trial_candidate: ['Trial candidate', 'مرشح للتجربة'],
  trial_in_progress: ['Trial in progress', 'التجربة جارية'],
  trial_passed: ['Trial passed', 'اجتاز التجربة'],
  approved: ['Approved', 'معتمد'],
  in_production: ['In production', 'قيد الإنتاج'],
  suspended: ['Suspended', 'معلّق'],
  superseded: ['Superseded', 'مُستبدَل'],
  retired: ['Retired', 'متوقف نهائياً'],
};
export const MEANING: Record<string, [string, string]> = {
  trial_reviewed: ['Trial reviewed', 'مراجعة التجربة'],
  approved: ['Approved', 'الاعتماد'],
  released: ['Released', 'الإفراج'],
  retired: ['Retired', 'الإيقاف النهائي'],
  suspended: ['Suspended', 'التعليق'],
  reinstated: ['Reinstated', 'إعادة التفعيل'],
  declared_values_accepted: ['Declared values accepted', 'قبول القيم المصرّح بها'],
};
